# application.yml? ???? ??? ??? ??
spring:
  profiles: # profiles ??
    active: local # ?? ??? ?? ? default ?? ?

# ?????
# java -jar -D spring.profiles.active={profile} api-0.0.1-SNAPSHOT.jar
# java -jar .\build\libs\??? jar???-1.0.0.jar --spring.profiles.active=??? ???